package com.example.service

import android.content.Context
import java.util.Random

object QuoteManager {

    val realityChecks = listOf(
        "Your future is getting fucked while you scroll like a dumbass.",
        "Competitors are grinding, tu yahan reels pe lund chus raha hai.",
        "Padhna toh padega, saale. Yeh dopamine ka chuttad mat ban.",
        "Every notification you open is another seat you’re kissing goodbye.",
        "Time waste kar raha hai? Result mein gaand phategi teri.",
        "Toppers are solving papers, you’re busy liking bullshit posts.",
        "Kal se padhunga attitude will fuck your entire life.",
        "Yeh phone tera baap nahi hai, iska gulam mat ban.",
        "You’re not resting, you’re just a weak addicted piece of shit.",
        "Exam hall mein yeh regret tere muh pe thappad marega.",
        "Har reel ek question banegi jo tujhe fail karegi.",
        "Aukaat nahi hai toh sapne dekhna band kar, chutiye.",
        "Your rank is dying every minute you waste on this garbage.",
        "Distractions ne teri life ki gaand maar li hai.",
        "Stop lying, motherfucker. You’re not studying at all.",
        "Yeh “thoda aur” wala scene tujhe road pe laayega.",
        "Future self already hates your guts for this bullshit.",
        "Clock nahi rukega, teri gaand pakad ke le jayega.",
        "Competitors ne 4 hours padh liye, tu abhi bhi chat pe hai.",
        "Yeh addiction tera selection ka gandha murderer hai.",
        "You chose cheap dopamine over your fucking dream.",
        "Result aayega toh sirf rona aur “kash” hi bachega.",
        "Phone ne tujhe bewakoof bana diya hai, samajh le.",
        "Average log scroll karte hain. Winners unko maar dete hain.",
        "Tera time barbaad ho raha hai aur tu has raha hai.",
        "Jab paper khali rahega, yaad aayega yeh moment.",
        "Stop betraying yourself, you spineless fuck.",
        "Notifications tere life ka control le chuke hain.",
        "Yeh break 2 ghante ka ho gaya, ab ro mat.",
        "Sapne bade hain, lekin discipline zero. Pathetic.",
        "Har ghanta waste = ek attempt ki gaand.",
        "Tu nahi so raha, tu apni future ko maar raha hai.",
        "Reels dekh ke kya milega? Sirf regret aur zero rank.",
        "Your competitors don’t give a fuck about your excuses.",
        "Phone rakh nahi pa raha? Toh haar maan le saale.",
        "Yeh “chill” mode tujhe lifetime loser bana dega.",
        "Distraction free nahi hua toh selection bhi nahi hoga.",
        "Time is fucking running, and you’re standing still.",
        "Exam ke din yeh guilt tujhe andar se kha jayega.",
        "Stop wasting your parents’ money on this bullshit habit.",
        "Your future is getting absolutely fucked while you scroll like an idiot.",
        "Competitors are solving papers, tu reels pe lund chus raha hai.",
        "Padhna toh padega saale, yeh dopamine ka chuttad mat ban.",
        "Every notification you tap is another seat you’re throwing away.",
        "Time waste kar raha hai? Result mein teri gaand phategi.",
        "Toppers grinding hard, you’re busy liking useless bullshit.",
        "Kal se padhunga attitude will destroy your entire fucking future.",
        "Yeh phone tera gulam nahi, tu iska gulam ban gaya hai.",
        "You’re not tired, you’re just a weak addicted piece of shit.",
        "Exam hall mein yeh moment tere muh pe thappad marega.",
        "Har reel ek blank question banega jo tujhe fail karega.",
        "Aukaat nahi hai toh bade sapne dekhna band kar chutiye.",
        "Your rank is bleeding out with every minute you waste.",
        "Distractions ne teri life ki gaand maar di hai.",
        "Stop bullshitting yourself, you’re not studying at all.",
        "Yeh “thoda aur” wala scene tujhe sadak pe laayega.",
        "Future self already regrets your weak-ass decisions.",
        "Clock doesn’t give a fuck about your excuses.",
        "Competitors ne 5 chapters khatam kiye, tu abhi chat pe hai.",
        "Yeh addiction tera selection ka gandha killer hai.",
        "You traded your dream for cheap dopamine hits.",
        "Result aayega toh sirf rona aur “kash” bachega.",
        "Phone ne tujhe bewakoof bana diya hai.",
        "Average students scroll. Winners delete that shit.",
        "Tera time barbaad ho raha, aur tu hans raha hai.",
        "Paper khali rahega toh yeh exact moment yaad aayega.",
        "Stop betraying your own blood, you spineless fuck.",
        "Notifications have taken full control of your life.",
        "Yeh break 3 hours ka ho gaya, ab mat rona.",
        "Sapne bade, discipline zero. Fucking pathetic.",
        "Har ghanta waste = ek full attempt ki gaand.",
        "Tu apni future ko dheere dheere maar raha hai.",
        "Reels dekh ke kya milega? Sirf regret aur zero rank.",
        "Competitors don’t give a single fuck about your excuses.",
        "Phone rakh nahi pa raha? Toh haar maan le saale.",
        "Yeh chill mode tujhe lifetime loser bana dega.",
        "Distraction free nahi hua toh selection sapna hi rahega.",
        "Time is fucking running out, and you’re standing still.",
        "Exam ke din yeh guilt tujhe andar se kha jayega.",
        "Parents ka paisa phone pe uda raha hai tu.",
        "Your dream college rejects weak phone addicts.",
        "Har push notification ek nail in your future’s coffin.",
        "Tu soch raha hai “bas 5 min”, life soch rahi hai goodbye.",
        "Toppers abhi bhi padh rahe hain, tu kya kar raha hai?",
        "Yeh scrolling addiction tera sabse bada enemy hai.",
        "Result day pe yeh moment tere dil mein goli marega.",
        "Phone ke peeche mat mar, apni aukaat pe mar.",
        "You’re choosing temporary pleasure over permanent success.",
        "Kal ke sapne aaj ke scrolling se mar rahe hain.",
        "Stop being a slave to your fucking notifications.",
        "Jab rank list mein naam nahi hoga, yeh scroll yaad aayega.",
        "Competitors are pulling ahead while you rot in reels.",
        "Yeh “just checking” habit tera career ka murderer hai.",
        "Time nahi mil raha? Tu khud time ko maar raha hai.",
        "Weak mind, strong phone addiction. Sad reality.",
        "Exam hall silence mein yeh guilt tere saath baith jayega.",
        "Padhne ki jagah tu dopamine ka bhikari ban gaya.",
        "Your future self is screaming at you right now.",
        "Har wasted hour = one less chance at your dream seat.",
        "Tu nahi jaag raha, tu apni life ko sula raha hai.",
        "Notifications tere control mein nahi, tu unke control mein hai.",
        "This phone is costing you your fucking destiny.",
        "Average log break mein bhi scroll karte hain.",
        "Result aane wala hai, abhi bhi bewakoofi kar raha?",
        "Yeh addiction chhod nahi pa raha toh selection bhi nahi milega.",
        "Your competitors don’t take “mental health breaks” every 10 mins.",
        "Phone rakh, warna zindagi bhar rakhna padega regret.",
        "Time is the only thing you can’t buy back, saale.",
        "Tu apne sapno ka sabse bada traitor ban raha hai.",
        "Distractions ne tujhe mentally bankrupt kar diya hai.",
        "Jab rank nahi aayega, yeh scroll yaad karke roega.",
        "Competitors subah 4 baje uth ke padh rahe hain, tu abhi bhi feed mein hai.",
        "Yeh “thoda sa check” tera pura saal barbaad kar dega.",
        "Phone addiction ne tujhe mentally bankrupt kar diya hai saale.",
        "Future self abhi bhi gaaliyan de raha hai tere is scrolling ko.",
        "Har push notification ek bullet in your dream’s head.",
        "Tu soch raha hai rest, duniya soch rahi hai loser.",
        "Aukaat ke bahar ke sapne aur aukaat ke andar ka phone time.",
        "Exam ke din yeh guilt tere paper pe bhi dikhega.",
        "Toppers ka phone silent mode pe hai, tera full volume pe.",
        "Yeh dopamine loop tujhe zindagi bhar ghumayega.",
        "Time running out hai aur tu reels ke saath timepass kar raha.",
        "Parents ke sapne tu phone pe uda raha hai.",
        "Weak hai tu notifications ke saamne, admit kar le.",
        "Result day pe “kash phone na dekhta” bolega.",
        "Har wasted minute = ek question less in your score.",
        "Tu apne competitors se peeche nahi, bahut peeche hai.",
        "Yeh habit tera selection ka sabse bada roadblock hai.",
        "Phone rakhne ki himmat nahi? Toh sapne chhod de.",
        "Future doctor/engineer banne wala abhi reels dekh raha hai. Pathetic.",
        "Clock tujhe ignore kar raha hai kyuki tu usko ignore kar raha.",
        "Yeh scrolling tera career ko dheere dheere maar raha hai.",
        "Competitors grind kar rahe, tu sirf justification kar raha.",
        "Exam hall mein yeh moment tere dimag mein ghus jayega.",
        "Tu worthy nahi lag raha is competition ke liye abhi.",
        "Har notification ne tujhe hijack kar liya hai.",
        "Kal se nahi, aaj se hi regret shuru ho chuka hai.",
        "Yeh phone tere haathon mein nahi, tere dimag mein baitha hai.",
        "Average banne ka full effort de raha hai tu.",
        "Time ki kadar nahi toh success ki umeed bhi mat rakh.",
        "Reels khatam nahi hote, lekin tere attempts khatam ho jayenge.",
        "Tu apni life ka sabse bada time thief ban gaya hai.",
        "Top rank waale abhi bhi padh rahe, tu kya justify kar raha?",
        "Yeh “bas 2 minute” 2 ghante ban chuka hai.",
        "Distractions tere sapno ka khoon choos rahe hain.",
        "Jab rank list aayegi, yeh moment sabse bada villain hoga.",
        "Phone ne tujhe bewakoof aur gareeb dono bana diya.",
        "Tu nahi lad raha, tu surrender kar raha hai.",
        "Har scroll ek step backward towards failure.",
        "Competitors ka focus iron hai, tera paper jaisa.",
        "Yeh addiction chhod nahi paaya toh kuch nahi jeet paayega.",
        "Future mein “phone ne barbaad kiya” mat bolna.",
        "Time barbaad karne ka mazaa ab regret mein badlega.",
        "Tu apne maa-baap ke investment ko waste kar raha hai.",
        "Notifications tere life ke boss ban chuke hain.",
        "Padhne ki jagah tu entertainment ka bhikari ban gaya.",
        "Yeh moment tere selection ka antim sanskar kar raha hai.",
        "Weak students scroll. Real warriors delete apps.",
        "Tera “chill” phase tere career ko khatam kar dega.",
        "Exam se pehle yeh guilt tere andar bomb ban jayega.",
        "Competitors aage badh rahe, tu reels mein atak gaya.",
        "Yeh phone tujhe jeetne nahi dega, samajh le saale.",
        "Har minute waste = ek year of regret.",
        "Tu apni aukaat se bada sapna dekh raha, chhota effort de raha.",
        "Result aayega toh sirf yeh scrolling yaad rahega.",
        "Phone ke saamne haar maan liya tune.",
        "Toppers ka break bhi short, tera break full movie.",
        "Yeh habit tujhe middle class trap mein daal degi.",
        "Future self abhi ro raha hai tere decisions pe.",
        "Tu worthy nahi is high-stakes game ke agar yeh continue kiya.",
        "Notifications ne tera focus ka murder kar diya.",
        "Time god nahi maanta tere “kal se” wale excuses.",
        "Reels dekh ke jeetne wale kabhi nahi dekhe tune.",
        "Yeh scrolling tera sabse bada self-sabotage hai.",
        "Competitors padh rahe hain, tu abhi bhi yahan wastage kar raha.",
        "Exam ke pressure mein yeh guilt tujhe tod dega.",
        "Phone rakhne ki himmat la, warna zindagi bhar rone ka.",
        "Tu apne dream ka murderer ban raha hai dheere dheere.",
        "Average log yahi karte hain. Tu average hi rahega.",
        "Har tap on screen ek nail in your rank’s coffin.",
        "Yeh addiction tujhe kabhi topper nahi banne dega.",
        "Time running out loud and clear, tu sun nahi raha.",
        "Future doctor abhi reels mein doctor play kar raha hai.",
        "Yeh moment tera sabse bada regret ban chuka hai.",
        "Stop fooling yourself. You’re losing badly.",
        "Competitors ka phone off, tera full entertainment system.",
        "Yeh “just checking” tera career destroy kar raha.",
        "Padhna toh padega, warna baad mein bahut padhega regret.",
        "Tu apni life ka remote control phone ke haath mein de chuka.",
        "Weak mind wins zero seats.",
        "Result day pe yeh scroll tere muh pe thookega.",
        "Phone ne tujhe gulam bana diya, ab jaag ja.",
        "Har wasted hour is a middle finger to your future.",
        "Tu nahi soch raha, tu bhag raha hai reality se.",
        "Toppers grind, tu grind karne ka drama kar raha.",
        "Yeh dopamine tera sabse bada traitor hai.",
        "Exam hall mein yeh guilt tujhe andar se jala dega.",
        "Competitors aage, tu peeche scrolling ke saath.",
        "Time ki kadar kar nahi pa raha toh kuch nahi hoga.",
        "Yeh habit tujhe lifetime “almost selected” banayegi.",
        "Phone addiction = dream assassination.",
        "Tu apne parents ke sapno ko daily kill kar raha.",
        "Future self already gave up on you.",
        "Har notification ek step towards average life.",
        "Tu worthy nahi lag raha is war ke liye.",
        "Reels khatam, lekin tere chances khatam ho chuke.",
        "Yeh scrolling tera permanent failure ka reason banega.",
        "Competitors nahi ruk rahe, tu kyun ruk raha?",
        "Phone ke peeche mat mar, apni life ke peeche mar.",
        "Yeh moment tujhe kabhi maaf nahi karega.",
        "Tu apni aukaat bhool chuka hai.",
        "Time waste ka asli daam result mein dena padega.",
        "Weak hai tu, admit kar aur sudhar.",
        "Notifications tere jeene ka tareeka ban gaye hain.",
        "Yeh addiction chhod, warna selection chod dega.",
        "Future rank zero because of current bullshit.",
        "Tu nahi lad raha is race mein.",
        "Har scroll ek suicide to your ambition.",
        "Competitors grinding, tu dying slowly.",
        "Yeh phone tera sabse bada enemy hai ab.",
        "Result aayega toh sirf rona rahega.",
        "Padhne ki jagah entertainment kar raha.",
        "Time god is watching your waste.",
        "Tu apna future khud barbaad kar raha.",
        "Weak decisions = weak life.",
        "Yeh “5 min” tera saal kha chuka.",
        "Competitors ka focus, tera distraction.",
        "Phone ne tujhe barbaad kar diya.",
        "Exam pressure mein yeh regret maar dega.",
        "Tu average banne ka full plan execute kar raha.",
        "Har tap kills one dream.",
        "Future self hates you right now.",
        "Yeh scrolling tera career ka antim sanskar.",
        "Tu worthy nahi agar yeh continue kiya.",
        "Stop. Your future is bleeding."
    ).distinct()

    val adrenalinePumps = listOf(
        "Put the fucking phone down and lock in right now.",
        "Grind kar, warna zindagi bhar gaand marwa.",
        "Timer on. Distractions ko fuck off bol.",
        "Lock the fuck in or get destroyed in the exam.",
        "Padhle madarchod, baad mein rona mat.",
        "Competitors jaise padh, warna unke peeche hi reh.",
        "No more bullshit. Books khol aur shuru ho ja.",
        "Phone side kar, brain on kar, abhi.",
        "Fuck the notifications. Study like your life depends on it.",
        "Aukaat dikha saale. Beast mode ON.",
        "Every second you delay is another seat gone, motherfucker.",
        "Stop thinking. Start fucking grinding.",
        "Yeh session complete kar, baaki duniya baad mein.",
        "Tu topper banega ya chu**iya banega? Decide now.",
        "Lock in so hard your distractions start crying.",
        "Gaand mein dum hai toh timer laga aur padh.",
        "No more “bas ek video”. Pure focus, abhi.",
        "Competitors nahi soye, tu kyun apni gaand bacha raha hai?",
        "Padh le bhenchod, warna sapne chod de.",
        "Crush this session like you want to crush the competition.",
        "Distraction free. Zero bakchodi. Full savage mode.",
        "Abhi shuru kar, warna lifetime regret shuru hoga.",
        "Timer laga. World ko mute kar. Lock in.",
        "Be the ruthless student your future self will respect.",
        "Gaali khani hai ya selection jeetna hai? Choose fast.",
        "Stop scrolling, start destroying questions.",
        "Hard work kar, baaki sab bakchodi hai saale.",
        "Lock in so brutally that even apps get scared.",
        "Yeh moment tera hai. Waste mat kar, chutiye.",
        "Phone band kar. Brain ON. Let’s fucking destroy it.",
        "Competitors ko peeche chhod, ab tera time hai.",
        "No mercy for distractions. Study like a machine.",
        "Timer shuru. Mind locked. Future secured, motherfucker.",
        "Padh le warna zindagi bhar “kash” bolta rahega.",
        "Become fucking unstoppable. Start this session now.",
        "Distractions ko delete kar. Discipline ko fuck in.",
        "Abhi ka pain kal ka top rank banega.",
        "No half-assed shit. Full savage focus.",
        "Tu jeetega, lekin abhi action lena padega bhenchod.",
        "Lock in. Grind hard. Fuck the competition.",
        "Phone side kar. Timer shuru kar. Abhi, saale.",
        "Lock the fuck in or get left in the dust forever.",
        "Distractions chod, warna selection tujhe chod dega.",
        "Grind mode ON. No more bakchodi allowed.",
        "Match the energy of your competitors right now.",
        "Timer laga. Notifications ko fuck off bol.",
        "Abhi rukega toh kabhi nahi pahunchega.",
        "Fuck the reels. Fuck the likes. Study like hell.",
        "Aukaat dikha. Phone rakh aur beast mode on.",
        "Every second delayed is a seat gone, motherfucker.",
        "Stop thinking. Start fucking solving.",
        "Yeh session complete kar. Baaki duniya baad mein.",
        "Topper banega ya chu**iya? Decide right now.",
        "Lock in so hard your phone starts crying.",
        "Gaand mein dum hai toh books khol aur padh.",
        "No more “bas ek video”. Pure savage focus.",
        "Competitors nahi soye, tu kyun apni gaand bacha raha?",
        "Padh le bhenchod, warna sapne chod de.",
        "Crush this session like you want to crush the exam.",
        "Distraction free. Zero excuses. Full beast mode.",
        "Abhi shuru kar, warna lifetime regret shuru hoga.",
        "Timer laga. World mute. Lock the fuck in.",
        "Be the ruthless student your future will thank.",
        "Gaali khani hai ya selection jeetna hai? Choose.",
        "Stop scrolling. Start destroying the question bank.",
        "Hard work kar, baaki sab bakchodi hai.",
        "Lock in so brutally even apps get scared.",
        "Yeh moment tera hai. Waste mat kar chutiye.",
        "Phone band. Brain on. Let’s fucking destroy it.",
        "Competitors ko peeche chhodne ka time aa gaya.",
        "No mercy for distractions. Study like a machine.",
        "Timer shuru. Mind locked. Future secured.",
        "Padh le warna zindagi bhar “kash” bolega.",
        "Become fucking unstoppable. Start this session.",
        "Distractions delete. Discipline install.",
        "Abhi ka pain kal ka top rank banega.",
        "No half-assed attempts. Full savage mode.",
        "Tu jeetega, lekin action abhi lena padega.",
        "Lock in. Grind hard. Fuck the competition.",
        "Phone ko muh pe fenk aur padhai shuru kar.",
        "Timer on kar aur apni aukaat dikha saale.",
        "No more bullshit breaks. Pure focus only.",
        "Grind like your entire bloodline depends on it.",
        "Yeh session tere sapno ka turning point hai.",
        "Lock in harder than your competitors right now.",
        "Distractions ko gaali de aur padh madarchod.",
        "Time waste band. Success mode activate.",
        "Tu capable hai. Ab dikha dikha ke padh.",
        "Fuck comfort. Embrace the grind.",
        "Next Pomodoro destroy kar, beast.",
        "Phone addiction ko aaj hi maar daal.",
        "Lock in like selection depends on this hour.",
        "No excuses. Only results from now on.",
        "Grind kar saale, baaki sab timepass hai.",
        "Phone phenk aur padh madarchod, abhi.",
        "Lock in harder than your competitors right now.",
        "Timer on. Distractions ko maar daal.",
        "Grind like your seat depends on this hour.",
        "Ab rukega toh kabhi nahi pahunchega saale.",
        "Fuck distractions. Study like a beast.",
        "Aukaat dikha. Full savage session now.",
        "No more bakchodi. Pure focus activate.",
        "Timer laga aur apni life sudhaar.",
        "Lock the fuck in, king. No excuses.",
        "Yeh session tere sapno ko zinda karega.",
        "Competitors se aage nikal, abhi shuru kar.",
        "Phone band kar. Brain on kar. Destroy.",
        "Grind mode full power, motherfucker.",
        "Padhle bhenchod, tu jeetne wala hai.",
        "No mercy. Next session ko tod de.",
        "Timer shuru. World off. You on.",
        "Become the monster your dream needs.",
        "Distractions delete. Discipline on fire.",
        "Abhi lock in kar, baad mein jeet.",
        "Fuck comfort zone. Enter grind zone.",
        "Yeh hour tere future ko badal dega.",
        "Phone rakh. Questions maar.",
        "Lock in so hard even time gets scared.",
        "Tu capable hai. Ab dikha dikha ke padh.",
        "Next Pomodoro ko brutal bana.",
        "No half measures. Full savage only.",
        "Competitors wait nahi kar rahe. Catch up.",
        "Timer on. Beast mode activated.",
        "Padh le saale, selection tera hai.",
        "Fuck the phone. Embrace the pain.",
        "Yeh session tere rank ko boost karega.",
        "Lock in like a machine.",
        "Abhi shuru kar. No more delay.",
        "Grind kar, baaki sab bakwas hai.",
        "Tu topper banne wala hai. Prove it.",
        "Phone ko chod. Focus ko pakad.",
        "Destroy this session like a warrior.",
        "Timer up. Let’s fucking go again.",
        "No excuses. Only execution now.",
        "Aukaat dikha. Grind like hell.",
        "Lock in brutally. Win brutally.",
        "Yeh moment tera turning point hai.",
        "Competitors ko peeche chhod de ab.",
        "Full focus. Zero bakchodi.",
        "Padh madarchod, future thank karega.",
        "Timer laga. Mind locked in.",
        "Become unstoppable right fucking now.",
        "Distractions ko gaali de aur padh.",
        "Yeh session tere sapno ka fuel hai.",
        "Lock in harder. Grind heavier.",
        "No more weakness. Only power.",
        "Abhi action le, baad mein result le.",
        "Tu jeet sakta hai. Ab dikha.",
        "Phone silent. Brain loud. Study.",
        "Savage mode ON. Let’s destroy syllabus.",
        "Grind kar saale, yeh tera time hai.",
        "Lock in. No looking back.",
        "Timer shuru. Future secure kar.",
        "Fuck fear. Fuck distractions. Grind.",
        "Ab full power session kar.",
        "Tu worthy hai jeetne ka. Prove it.",
        "Next round ko tod ke rakh de.",
        "Lock in like your life depends on it.",
        "Padh le bhenchod, rank tera intezaar kar raha.",
        "No bullshit. Pure discipline.",
        "Competitors se aage nikal abhi.",
        "Yeh hour tere career ko badal dega.",
        "Grind without mercy.",
        "Timer on. Beast unlocked.",
        "Phone rakh. War shuru kar.",
        "Tu jeetega. Ab lock in kar.",
        "Full savage. No half-assed.",
        "Abhi padh, kal proud feel kar.",
        "Lock in. Destroy. Repeat.",
        "Yeh session tera game changer hai.",
        "Distractions off. Focus max.",
        "Grind like there’s no tomorrow.",
        "Timer laga. Aukaat dikha.",
        "No more delay. Pure execution.",
        "Tu monster hai. Wake up.",
        "Lock in harder than yesterday.",
        "Padhle saale, selection tere naam.",
        "Fuck everything else. Study only.",
        "Become the topper they fear.",
        "Timer shuru. Mind on fire.",
        "No excuses allowed anymore.",
        "Grind kar. Dream capture kar.",
        "Abhi lock in. Baad mein celebrate.",
        "Phone gone. Focus on.",
        "Tu iske layak hai. Dikha ab.",
        "Savage session start kar.",
        "Competitors ko crush kar.",
        "Lock in. Win this war.",
        "Full power. No stopping.",
        "Yeh tera time hai. Own it.",
        "Grind brutal. Result royal.",
        "Timer on. Destroy mode.",
        "Padh madarchod. Jeet madarchod.",
        "No weakness. Only strength.",
        "Lock in like a champion.",
        "Ab session shuru. No bakchodi.",
        "Tu topper hai. Act like it.",
        "Grind hard. Shine harder.",
        "Fuck distractions forever.",
        "Timer ready. You ready?",
        "Lock in. No mercy.",
        "Yeh hour tera hai. Take it.",
        "Become fucking unstoppable.",
        "Padh le. Rank le.",
        "Full beast. Zero mercy.",
        "Timer on. Win mode.",
        "Grind like hell. Succeed like king.",
        "Lock in now. Regret never.",
        "Tu jeetne wala. Start now.",
        "No more waste. Only grind.",
        "Phone off. Brain on.",
        "Destroy this Pomodoro.",
        "Lock in brutally hard.",
        "Abhi shuru. Future bright.",
        "Grind without limits.",
        "Tu capable. Prove daily.",
        "Timer up. Beast out.",
        "Lock in. Own your destiny.",
        "Let’s fucking win this."
    ).distinct()

    val breakQuotes = listOf(
        "Rest is not laziness; it is a vital part of growth. Breathe.",
        "Recharge your energy. Your mind deserves a peaceful pause.",
        "Disconnect for a few moments to reconnect even stronger.",
        "Relax, release tension, and let your mind wander.",
        "A mindful break clears the path for ultimate creativity.",
        "Inhale peace, exhale stress. Good job on your session!",
        "Rest when you're weary. Refresh and renew yourself.",
        "Taking time to rest is a gesture of self-respect.",
        "Give yourself permission to pause and appreciate progress.",
        "A rested brain is an inspired brain. Enjoy this moment.",
        "Quiet the mind and the soul will speak.",
        "Stretch your body, drink some water, and clear your gaze.",
        "Step back from the canvas of work to see the whole picture.",
        "Pause. Breathe. Smile. You are doing exceptionally well.",
        "Let your thoughts settle like petals on a quiet pond.",
        "True productivity includes knowing when to heal and rest.",
        "The rhythm of life requires both the stride and the pause.",
        "A brief rest restores the spirit and sharpens the intellect.",
        "Look out the window, find the sky, and remember your roots.",
        "Close your eyes for ten deep breaths. Let go of the hurry.",
        "Your mind is a sky; let the clouds of thoughts float away.",
        "Peace is not the absence of work; it is the presence of rest within.",
        "A glass of water, a deep stretch, a free mind.",
        "Gentle pauses create space for brilliant epiphanies.",
        "Allow your focus muscles to fully relax. You've earned it.",
        "Breathe in fresh inspiration, and blow out lingering fatigue.",
        "Pace yourself; the journey of knowledge is a beautiful marathon.",
        "Rest is the sacred soil in which focus takes root.",
        "Let your shoulders drop. Let your jaw soften. Just be.",
        "Stepping away is sometimes the fastest way to leap forward.",
        "Unload the mental stack. Empty your mind for a few minutes.",
        "The pauses between notes are what make the music beautiful.",
        "You have built momentum; now let it rest with grace.",
        "Take a minute to wander without a map.",
        "A break is the breath that supports your next great work.",
        "Savor this pause—it is the bridge between effort and reward.",
        "Nurture your clarity. Let your thoughts wander free.",
        "A moment of stillness can realign a whole day of focus.",
        "Give your focus a soft place to land before the next flight.",
        "You are precious, and your peace is paramount. Rest well.",
        "☕ Take a breath. Even beasts need to rest.",
        "🔋 Recharging the system. Step away from the screen.",
        "🧘 Good grind. Now let your brain absorb it.",
        "💧 Hydrate, stretch, and reset your mind.",
        "⚡ Rest now, so you can destroy the next session.",
        "🛡 Shield down for a moment. Relax.",
        "🏆 Small wins stack up. Enjoy your break.",
        "🌬 Breathe in success, exhale the stress.",
        "🌿 Walk around. Don't look at another screen.",
        "💪 Fuel up. The war isn't over yet."
    )

    fun getFreshQuote(context: Context, isBreak: Boolean, prefKey: String): String {
        val quotes = if (isBreak) breakQuotes else (realityChecks + adrenalinePumps).distinct()
        val prefs = context.getSharedPreferences("quote_prefs", Context.MODE_PRIVATE)
        val lastQuoteIndex = prefs.getInt(prefKey, -1)
        
        var attempts = 0
        var selectIndex = Random().nextInt(quotes.size)
        while (selectIndex == lastQuoteIndex && attempts < 10) {
            selectIndex = Random().nextInt(quotes.size)
            attempts++
        }
        
        prefs.edit().putInt(prefKey, selectIndex).apply()
        return quotes[selectIndex]
    }
}
